# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APISQLite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APISQLite

  #API Calling
  pod 'Alamofire'
  pod 'SwiftyJSON'

  #Image loading/Downloading
  pod 'SDWebImageWebPCoder'
    
  target 'APISQLiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APISQLiteUITests' do
    # Pods for testing
  end

end
